GoodVillages/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

import app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls',namespace='app')),
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
    # path('calendar/', include('django_bootstrap_calendar.urls')),

]
if settings.DEBUG :
    urlpatterns +=static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

app/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from app import views

app_name='app'
urlpatterns = [
    path('', views.dashboard,name='dashboard'),
    path('edit_personal_data/',views.edit_personal_data, name = 'edit_personal_data'),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),{'next_page': '/'}, name='logout'),
    path('register/',views.register,name='register'),
    path('create_task/',views.create_task,name = 'create_task'),
    path('task_list/', views.task_list, name='task_list'),
    path('task_edit/<int:year>/<int:month>/<int:day>/<slug:task>/', views.task_edit, name='task_edit'), #編輯主任務
    path('sub_task_add/<int:year>/<int:month>/<int:day>/<slug:task>/', views.sub_task_add, name='sub_task_add'),  # 編輯主任務
    path('invalidTask/<int:year>/<int:month>/<int:day>/<slug:task>/<int:vaild>', views.invalidTask, name='invalidTask'),  # 任務失效
    path('invalidTask/<int:year>/<int:month>/<int:day>/<slug:task>/<int:vaild>', views.invalidTask, name='invalidTask'),  # 任務生效
    path('personal_task_add/', views.persontask_add, name='personal_task_add'),
    path('generate_qr_code/<int:id>/<slug:task>', views.generate_qr_code, name='generate_qr_code'),
    path('update_personal_task/<int:id>/<int:user_id>/<slug:task>', views.update_personal_task, name='update_personal_task'),
    path('scan_qrcode/', views.scan_qrcode, name='scan_qrcode'),
    path('my_personal_tasks/', views.my_personal_tasks, name='my_personal_tasks'),
    path('vaild_my_person_task/',views.vaild_my_person_task,name='vaild_my_person_task'),

    #團隊任務 2021/01/28 mark
    path('create_team_tasks/', views.create_team_tasks, name='create_team_tasks'), # admin ->create team task
    path('team_task_list/',views.team_task_list,name = 'team_task_list'),
    path('my_team_tasks_link/', views.my_team_tasks_link, name='my_team_tasks_link'), #在工具列中點選，看出還有幾個任務可加入
    path('add_teamtask/<int:user_id>/<int:group_id>',views.add_teamtask,name='add_teamtask'),#舊版本我要加入
    path('add_sub_team_task/<int:year>/<int:month>/<int:day>/<slug:task>/', views.add_sub_team_task, name='add_sub_team_task'),  # 新增子任務方案
    path('sub_teamtask_list/',views.sub_teamtask_list,name='sub_teamtask_list'), # 團隊子任務列表
    path('validTeamTask/<int:year>/<int:month>/<int:day>/<slug:task>/<int:vaild>', views.invalidTeamTask, name='invalidTeamTask'),  # 團隊任務失效
    path('invalidTeamTask/<int:year>/<int:month>/<int:day>/<slug:task>/<int:vaild>', views.invalidTeamTask, name='invalidTeamTask'),  # 團隊任務生效
    path('generate_team_qr_code/<int:id>/<slug:task>', views.generate_team_qr_code, name='generate_team_qr_code'),
    path('update_team_task/<int:id>/<slug:task>', views.update_team_task, name='update_team_task'),
    path('team_task_proposal/<int:user_id>/<int:task_id>/',views.team_task_proposal,name = 'team_task_proposal'),#贊助活動
    path('participate_team_task/<int:user_id>/<int:task_id>/',views.participate_team_task_proposal,name = 'participate_team_task'),#贊助活動


    # path('confirm_teamtask/',views.confirm_teamtask,name = 'confirm_teamtask'),
    # path('create_team_tasks/', views.my_team_tasks_link, name='create_team_tasks'),
    # path('create_group/', views.create_group, name='create_group'),
    # path('manage_team_task/<int:task_id>/<int:group_id>/<int:user_id>/', views.manage_team_task, name='manage_team_task'),
    #懸賞任務
    path('manage_award_task/', views.manage_award_task, name='manage_award_task'),#懸賞主頁
    path('create_award_task',views.create_award_task, name= 'create_award_task'),# 發布任務
    path('release_award_task', views.release_award_task, name='release_award_task'),#管理者approve 任務
    path('approve_award_task/<int:award_task_id>', views.approve_award_task, name='approve_award_task'),
    path('accept_award_task/<int:award_task_id>/<int:user_id>', views.accept_award_task, name='accept_award_task'),#接受任務
    path('depoly_award_task/', views.depoly_award_task, name='depoly_award_task'),
    path('my_award_task/<int:user_id>',views.my_award_task,name = 'my_award_task'),#我的任務
    #工作任務
    path('manage_work_task/',views.manage_work_task,name ='manage_work_task'),
    path('create_work_task/', views.create_work_task, name='create_work_task'),
    path('assign_work_task/', views.assign_work_task, name='assign_work_task'),
    path('work_task_list/', views.work_task_list, name='work_task_list'),
    path('accept_work_task/<int:task_id>/<slug:task>', views.accept_work_task, name='accept_work_task'),
    path('worktask_start_count/<slug:task>',views.worktask_start_count,name='worktask_start_count'),
    path('worktask_end_count/<slug:task>',views.worktask_end_count,name='worktask_end_count'),
    path('worktask_vaildation/<slug:task>', views.worktask_vaildation, name='worktask_vaildation'),

    #個人點數
    path('manage_account_value/', views.manage_account_value, name='manage_account_value'),
    path('account_list/<int:id>/<slug:account_slug>',views.account_list,name='account_list'),
    #個人行事曆
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/<int:event_id>/details/', views.event_details, name='event-detail'),
    path('event/new/', views.create_event, name='event_new'),
    path('event/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'),

    #園區行事曆
    path('create_calendar/',views.create_calendar,name='create_calendar'),
    #我的
    path('my_account/', views.my_account, name='my_account'),

]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html itemscope itemtype='http://schema.org/WebPage'>

<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">



</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light"  >
  <a class="navbar-brand" href="#">好好聚落</a>
  <button class="navbar-toggler" type="button"
          data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   {% if request.user.is_authenticated %}
       {% if request.session.authority == 'resident' %}
    <div class="navbar-nav .nav-pills mr-auto">
      <li class="nav-item active"><h4>
          <a class="nav-link" href="{% url 'app:dashboard' %}">首頁 <span class="sr-only">(current)</span></a></h4>
      </li>
      <li class="nav-item"><h4>
        <a class="nav-link" href="{% url 'app:my_personal_tasks' %}">每日任務</a></h4>
      </li>
      <li class="nav-item"><h4>
        <a class="nav-link" href="{% url 'app:my_team_tasks_link' %}">團隊任務</a></h4>
      </li>
        <li class="nav-item"><h4>
        <a class="nav-link" href="{% url 'app:manage_award_task' %}">懸賞任務</a></h4>
      </li>
        <li class="nav-item"><h4>
        <a class="nav-link" href="{% url 'app:manage_work_task' %}">工作任務</a></h4>
      </li>

        <li class="nav-item"><h4>
          <a class="nav-link" href="{% url 'app:my_account' %}">我的點數</a>
        </h4></li>
{#    </div>#}


    {% endif %}

       {% if request.session.authority == 'admin' %}
           <ul class="navbar-nav mr-auto">
               <li class="nav-item dropdown">
                   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       住戶管理
                   </a>
                   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                       <a class="dropdown-item" href="{% url 'app:register' %}">住民註冊</a>
                       <a class="dropdown-item" href="{% url 'app:create_task' %}">創建個人任務</a>
                       <a class="dropdown-item" href="{% url 'app:task_list' %}">個人任務列表</a>
                       <a class="dropdown-item" href="{% url 'app:create_team_tasks' %}">創建團隊任務</a>
                       <a class="dropdown-item" href="{% url 'app:team_task_list' %}">團隊任務列表</a>
                       <a class="dropdown-item" href="{% url 'app:sub_teamtask_list' %}">團隊方案列表</a>
                       <a class="dropdown-item" href="{% url 'app:release_award_task' %}">懸賞任務審核</a>
                       <a class="dropdown-item" href="{% url 'app:scan_qrcode'%}">個人任務登記</a>
                       <a class="dropdown-item" href="{% url 'app:create_work_task' %}">創建工作任務</a>
                       <a class="dropdown-item" href="{% url 'app:assign_work_task' %}">工作任務指派</a>
                       <a class="dropdown-item" href="{% url 'app:work_task_list' %}">工作任務列表</a>

                       <a class="dropdown-item" href="{% url 'app:create_calendar' %}">園區行事曆</a>
                       <a class="dropdown-item" href="{% url 'app:manage_account_value' %}">個人點數加值</a>


                   </div>
               </li>
           </ul>
       {% endif %}

   {% endif %} </div>
<span class="navbar-text" >
            <a  href="{% url 'app:edit_personal_data' %}">{{ request.user.userprofile }}</a>
            </span>
<ul>
            <span class="navbar-text" >
         <a href="{% url 'app:logout'  %}">登出</a>
            </span>
</ul>
      </div>

</nav>

    {% block content %}
    {% endblock %}

</body>
</html>

app/templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'app:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

app/templates/pagination.html
{% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">上一頁</a>
{% endif %}

 {% if page.has_next %}
    <a href="?page={{ page.next_page_number  }}">下一頁</a>
{% endif %}